# Generated by Django 5.0.7 on 2025-06-27 18:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0001_initial'),
        ('storefinder_api', '0002_category_alter_store_options_store_opening_hours_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='storefinder_api.store'),
        ),
    ]
