# Generated by Django 5.0.7 on 2025-07-26 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_url',
            field=models.URLField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name='product',
            name='search_term',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='source_site',
            field=models.CharField(max_length=100),
        ),
    ]
