# Generated by Django 5.0.7 on 2025-07-26 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0002_product_product_url_product_search_term_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_url',
            field=models.URLField(unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='search_term',
            field=models.CharField(max_length=255),
        ),
    ]
